const mongoose = require('mongoose');
const Schema = mongoose.Schema;

/**
 * ArchiveSnapshot - append-only event log of academic snapshots.
 *
 * Generated automatically during Academic Year Rollover. Each document is an
 * immutable, denormalized point-in-time report. These records are NEVER
 * updated or deleted (enforced by middleware below).
 *
 * This is NOT the Student Documents module. Personal student files
 * (birth certificates, transcripts, etc.) do not belong here.
 */
const archiveSnapshotSchema = new Schema({
  type: {
    type: String,
    required: true,
    enum: [
      'ENROLLMENT_SNAPSHOT',
      'PROMOTION_REPORT',
      'RETENTION_REPORT',
      'GRADUATION_REPORT',
      'BLOCK_SNAPSHOT',
      'ROLLOVER_AUDIT',
      'STUDENT_ARCHIVE',
      'GRADES_ARCHIVE',
    ],
    index: true
  },
  title: {
    type: String,
    required: true,
    trim: true
  },
  // The school year that was closed by the rollover
  schoolYear: {
    type: String,
    required: true,
    match: [/^\d{4}-\d{4}$/, 'Please enter a valid school year format (YYYY-YYYY)'],
    index: true
  },
  // The school year that was opened by the rollover
  newSchoolYear: {
    type: String,
    match: [/^\d{4}-\d{4}$/, 'Please enter a valid school year format (YYYY-YYYY)']
  },
  semester: {
    type: String,
    enum: ['1st', '2nd', 'Summer']
  },
  // Groups all snapshots generated by a single rollover run
  rolloverBatchId: {
    type: String,
    required: true,
    index: true
  },
  // Denormalized point-in-time payload. Never referenced live data.
  data: {
    type: Schema.Types.Mixed,
    required: true
  },
  counts: {
    total: { type: Number, default: 0 },
    promoted: { type: Number, default: 0 },
    retained: { type: Number, default: 0 },
    graduated: { type: Number, default: 0 },
    skipped: { type: Number, default: 0 }
  },
  generatedBy: {
    type: Schema.Types.ObjectId,
    ref: 'Admin',
    required: true
  }
}, {
  timestamps: {
    createdAt: 'generatedAt',
    updatedAt: false
  }
});

archiveSnapshotSchema.index({ schoolYear: 1, type: 1, generatedAt: -1 });
archiveSnapshotSchema.index({ generatedAt: -1 });

// Append-only enforcement: snapshots can never be updated or deleted.
function rejectMutation(next) {
  next(new Error('Archive snapshots are immutable and cannot be modified or deleted.'));
}

archiveSnapshotSchema.pre('save', function(next) {
  if (!this.isNew) {
    return next(new Error('Archive snapshots are immutable and cannot be modified.'));
  }
  next();
});

archiveSnapshotSchema.pre('findOneAndUpdate', rejectMutation);
archiveSnapshotSchema.pre('updateOne', rejectMutation);
archiveSnapshotSchema.pre('updateMany', rejectMutation);
archiveSnapshotSchema.pre('findOneAndDelete', rejectMutation);
archiveSnapshotSchema.pre('deleteOne', { document: false, query: true }, rejectMutation);
archiveSnapshotSchema.pre('deleteMany', rejectMutation);

module.exports = mongoose.model('ArchiveSnapshot', archiveSnapshotSchema);
